import { getEnv } from "@/utils/env.util";

export const SENTRY_DSN = getEnv("EXPO_PUBLIC_SENTRY_DSN");
export const CLERK_PUBLISHABLE_KEY = getEnv(
  "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY",
);
export const REVENUECAT_IOS_API_KEY = getEnv(
  "EXPO_PUBLIC_REVENUECAT_IOS_API_KEY",
);
export const REVENUECAT_ANDROID_API_KEY = getEnv(
  "EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY",
);

export const EXPO_PUBLIC_REVENUECAT_TEST_API_KEY = getEnv(
  "EXPO_PUBLIC_REVENUECAT_TEST_API_KEY",
);
