import { Routine } from '@/types/routine.types';

export const ROUTINES: Routine[] = [
  {
    id: 'hard_mewing_hold',
    name: 'Hard Mewing Hold',
    duration: 5,
    summary:
      'Trains strong tongue posture to support midface lift and facial balance.',
    image: require('@/assets/images/routines/hard_mewing_hold.jpg'),
    products: [],
    primaryTargets: ['midface_ratio'],
    secondaryTargets: ['overall_symmetry', 'jawline_symmetry'],
    steps: [
      { order: 1, instruction: 'Close your mouth and keep lips sealed.' },
      {
        order: 2,
        instruction:
          "Place your tongue on the roof of your mouth using the 'ng' position.",
      },
      {
        order: 3,
        instruction: 'Press the entire tongue firmly against the palate.',
      },
      { order: 4, instruction: 'Keep teeth lightly touching.' },
      { order: 5, instruction: 'Breathe through your nose.' },
      { order: 6, instruction: 'Hold for 2–3 minutes and repeat 2–3 times.' },
    ],
  },
  {
    id: 'masseter_balance_training',
    name: 'Masseter Balance Training',
    duration: 5,
    summary: 'Strengthens jaw muscles evenly to improve jawline symmetry.',
    image: require('@/assets/images/routines/masseter_balance_training.jpg'),
    products: [],
    primaryTargets: ['jawline_symmetry'],
    secondaryTargets: ['chin_alignment', 'overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Sit upright with lips closed.' },
      { order: 2, instruction: 'Place one hand under your chin.' },
      {
        order: 3,
        instruction: 'Open your mouth slowly against light resistance.',
      },
      { order: 4, instruction: 'Close slowly back to neutral.' },
      { order: 5, instruction: 'Repeat 10 times.' },
      {
        order: 6,
        instruction: 'Push jaw gently against resistance on each side.',
      },
    ],
  },
  {
    id: 'neck_curls_extensions',
    name: 'Neck Curls & Extensions',
    duration: 6,
    summary:
      'Strengthens neck muscles to support jawline definition and posture.',
    image: require('@/assets/images/routines/neck_curls_extensions.jpg'),
    products: [{ name: 'Dumbbell', optional: true }],
    primaryTargets: ['jawline_symmetry'],
    secondaryTargets: ['facial_thirds', 'overall_symmetry'],
    steps: [
      {
        order: 1,
        instruction: 'Lie on your back with head slightly off the edge.',
      },
      { order: 2, instruction: 'Place light weight on forehead.' },
      { order: 3, instruction: 'Lift chin toward chest slowly.' },
      { order: 4, instruction: 'Lower head back down with control.' },
      { order: 5, instruction: 'Repeat 20–30 reps.' },
      {
        order: 6,
        instruction: 'Flip face down and repeat for neck extensions.',
      },
    ],
  },
  {
    id: 'chin_tucks',
    name: 'Chin Tucks',
    duration: 7,
    summary: 'Corrects forward head posture and improves profile balance.',
    image: require('@/assets/images/routines/chin_tucks.jpg'),
    products: [{ name: 'Mirror', optional: true }],
    primaryTargets: ['facial_thirds'],
    secondaryTargets: ['chin_alignment', 'overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Stand or sit tall.' },
      { order: 2, instruction: 'Place hand on forehead.' },
      { order: 3, instruction: 'Push head forward while resisting with hand.' },
      { order: 4, instruction: 'Hold for 8–10 seconds.' },
      { order: 5, instruction: 'Relax and repeat 8–10 times.' },
    ],
  },
  {
    id: 'wall_posture_reset',
    name: 'Wall Posture Reset',
    duration: 4,
    summary: 'Aligns spine, neck and head to improve facial symmetry.',
    image: require('@/assets/images/routines/wall_posture_reset.jpg'),
    products: [{ name: 'Wall' }],
    primaryTargets: ['facial_thirds'],
    secondaryTargets: ['overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Stand with back and head touching the wall.' },
      { order: 2, instruction: 'Keep heels slightly away from the wall.' },
      { order: 3, instruction: 'Pull shoulder blades together.' },
      { order: 4, instruction: 'Tuck your chin slightly.' },
      { order: 5, instruction: 'Hold for 1 minute and repeat.' },
    ],
  },
  {
    id: 'scm_neck_stretch',
    name: 'SCM Neck Stretch',
    duration: 4,
    summary: 'Releases tight neck muscles that may cause jaw tilt.',
    image: require('@/assets/images/routines/scm_neck_stretch.jpg'),
    products: [],
    primaryTargets: ['jawline_symmetry'],
    secondaryTargets: ['overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Sit upright with shoulders relaxed.' },
      { order: 2, instruction: 'Tilt head sideways until stretch is felt.' },
      { order: 3, instruction: 'Turn chin upward slightly.' },
      { order: 4, instruction: 'Hold for 25–30 seconds.' },
      { order: 5, instruction: 'Repeat on the other side.' },
    ],
  },
  {
    id: 'mandibular_fascia_release',
    name: 'Mandibular Fascia Release',
    duration: 4,
    summary: 'Relieves jaw tension to improve facial balance.',
    image: require('@/assets/images/routines/mandibular_fascia_release.jpg'),
    products: [{ name: 'Facial Oil', optional: true }],
    primaryTargets: ['jawline_symmetry'],
    secondaryTargets: ['chin_alignment'],
    steps: [
      { order: 1, instruction: 'Apply oil along the jawline.' },
      { order: 2, instruction: 'Place fingers under cheekbones.' },
      { order: 3, instruction: 'Massage in small circles.' },
      { order: 4, instruction: 'Move toward the chin slowly.' },
      { order: 5, instruction: 'Glide fingers down the neck.' },
    ],
  },
  {
    id: 'gua_sha_jawline',
    name: 'Gua Sha Jawline',
    duration: 5,
    summary: 'Reduces facial puffiness and enhances jaw definition.',
    image: require('@/assets/images/routines/gua_sha_jawline.jpg'),
    products: [{ name: 'Gua Sha Stone' }, { name: 'Facial Oil' }],
    primaryTargets: ['facial_puffiness'],
    secondaryTargets: ['jawline_symmetry', 'cheekbone_balance'],
    steps: [
      { order: 1, instruction: 'Apply facial oil.' },
      { order: 2, instruction: 'Hold the Gua Sha tool at a shallow angle.' },
      { order: 3, instruction: 'Glide from chin toward the ear.' },
      { order: 4, instruction: 'Sweep cheeks from nose to temples.' },
      { order: 5, instruction: 'Repeat each motion 5–10 times.' },
    ],
  },
  {
    id: 'cheekbone_lift_massage',
    name: 'Cheekbone Lift Massage',
    duration: 4,
    summary: 'Stimulates cheek muscles to improve cheekbone definition.',
    image: require('@/assets/images/routines/cheekbone_lift_massage.jpg'),
    products: [{ name: 'Facial Oil', optional: true }],
    primaryTargets: ['cheekbone_balance'],
    secondaryTargets: ['facial_puffiness'],
    steps: [
      { order: 1, instruction: 'Apply facial oil.' },
      { order: 2, instruction: 'Place fingers under cheekbones.' },
      { order: 3, instruction: 'Lift upward in circular motions.' },
      { order: 4, instruction: 'Hold lifts for 2 seconds.' },
      { order: 5, instruction: 'Repeat 15–20 times per side.' },
    ],
  },
  {
    id: 'smile_symmetry_routine',
    name: 'Smile Symmetry Routine',
    duration: 4,
    summary: 'Trains mouth muscles to move evenly for a balanced smile.',
    image: require('@/assets/images/routines/smile_symmetry_routine.jpg'),
    products: [{ name: 'Mirror', optional: true }],
    primaryTargets: ['overall_symmetry'],
    secondaryTargets: ['chin_alignment'],
    steps: [
      { order: 1, instruction: 'Stand in front of a mirror.' },
      { order: 2, instruction: 'Smile slowly.' },
      { order: 3, instruction: 'Ensure both corners lift evenly.' },
      { order: 4, instruction: 'Hold for 3 seconds.' },
      { order: 5, instruction: 'Repeat 15–20 times.' },
    ],
  },
  {
    id: 'orb_oculi_training',
    name: 'Orb Oculi Training',
    duration: 4,
    summary: 'Strengthens muscles around the eyes for balanced eye movement.',
    image: require('@/assets/images/routines/orb_oculi_training.jpg'),
    products: [{ name: 'Mirror', optional: true }],
    primaryTargets: ['eye_alignment'],
    secondaryTargets: ['eyebrow_symmetry'],
    steps: [
      { order: 1, instruction: 'Look in a mirror.' },
      { order: 2, instruction: 'Place fingers at outer eye corners.' },
      {
        order: 3,
        instruction: 'Squint slightly while resisting with fingers.',
      },
      { order: 4, instruction: 'Hold 2 seconds then relax.' },
      { order: 5, instruction: 'Repeat 15–20 times.' },
    ],
  },
  {
    id: 'wall_posture_training',
    name: 'Wall Posture Training',
    duration: 5,
    summary: 'Improves posture and head alignment to support facial symmetry.',
    image: require('@/assets/images/routines/wall_posture_training.jpg'),
    products: [{ name: 'Wall', optional: false }],
    primaryTargets: ['facial_thirds'],
    secondaryTargets: ['overall_symmetry', 'jawline_symmetry'],
    steps: [
      {
        order: 1,
        instruction: 'Stand with heels about 5 cm away from a wall.',
      },
      {
        order: 2,
        instruction:
          'Press your back, shoulders, and head gently against the wall.',
      },
      {
        order: 3,
        instruction: 'Keep your chin slightly tucked and neck straight.',
      },
      { order: 4, instruction: 'Pull shoulder blades together lightly.' },
      { order: 5, instruction: 'Hold the position for 1 minute.' },
      { order: 6, instruction: 'Rest for 20 seconds.' },
      { order: 7, instruction: 'Repeat 3 times.' },
      {
        order: 8,
        instruction:
          'Walk away from the wall while maintaining the same posture.',
      },
    ],
  },
  {
    id: 'neck_stretch',
    name: 'Neck Stretch',
    duration: 4,
    summary:
      'Releases neck tension that can tilt the head and affect facial balance.',
    image: require('@/assets/images/routines/neck_stretch.jpg'),
    products: [],
    primaryTargets: ['facial_thirds'],
    secondaryTargets: ['jawline_symmetry', 'overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Sit or stand tall with shoulders relaxed.' },
      {
        order: 2,
        instruction:
          'Tilt your head slowly to one side until you feel a stretch.',
      },
      {
        order: 3,
        instruction: 'Hold for 25–30 seconds while breathing slowly.',
      },
      { order: 4, instruction: 'Return to center.' },
      { order: 5, instruction: 'Repeat on the other side.' },
      {
        order: 6,
        instruction: 'Turn your head gently left and right a few times.',
      },
      {
        order: 7,
        instruction:
          'Drop your chin slightly to stretch the back of your neck.',
      },
      { order: 8, instruction: 'Finish with slow shoulder rolls.' },
    ],
  },
  {
    id: 'nose_centering_routine',
    name: 'Nose Centering Routine',
    duration: 4,
    summary: 'Gentle routine intended to encourage a centered nose appearance.',
    image: require('@/assets/images/routines/nose_centering_routine.jpg'),
    products: [],
    primaryTargets: ['nose_centering'],
    secondaryTargets: ['overall_symmetry'],
    steps: [
      { order: 1, instruction: 'Sit or stand straight and relax your face.' },
      {
        order: 2,
        instruction: 'Place your thumb on the side where the nose tilts.',
      },
      { order: 3, instruction: 'Gently push that side toward the center.' },
      { order: 4, instruction: 'Hold the pressure for 10–15 seconds.' },
      { order: 5, instruction: 'Relax and repeat 5–6 times.' },
      { order: 6, instruction: 'Place both thumbs on each side of the nose.' },
      { order: 7, instruction: 'Push gently downward toward the tip.' },
      {
        order: 8,
        instruction: 'Hold for 10 seconds and repeat several times.',
      },
      {
        order: 9,
        instruction: 'Finish by sliding fingers down the sides of the nose.',
      },
    ],
  },
];
